//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int TestId { get; set; }
        public string TestName { get; set; }
        public string TestDescription { get; set; }
        public Nullable<System.DateTime> TestDeadline { get; set; }
        public string TestType { get; set; }
        public Nullable<int> NumberOfQuestions { get; set; }
        public Nullable<System.DateTime> TestAvailabilitySpan { get; set; }
        public string AttendantsSection { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
