//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Courses = new HashSet<Courses>();
            this.GroupMembers = new HashSet<GroupMembers>();
            this.Groups = new HashSet<Groups>();
            this.Messages = new HashSet<Messages>();
            this.ModuleUser = new HashSet<ModuleUser>();
            this.Pages = new HashSet<Pages>();
            this.UsersInCourse = new HashSet<UsersInCourse>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Forums = new HashSet<Forums>();
            this.Homeworks = new HashSet<Homeworks>();
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string StudentIdentificationNumber { get; set; }
        public string AccessStatus { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual ICollection<GroupMembers> GroupMembers { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<ModuleUser> ModuleUser { get; set; }
        public virtual ICollection<Pages> Pages { get; set; }
        public virtual ICollection<UsersInCourse> UsersInCourse { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Forums> Forums { get; set; }
        public virtual ICollection<Homeworks> Homeworks { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}
