//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public Grades()
        {
            this.CourseModule = new HashSet<CourseModule>();
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int GradeId { get; set; }
        public Nullable<decimal> GradeValue { get; set; }
        public Nullable<System.DateTime> Gradedatetime { get; set; }
    
        public virtual ICollection<CourseModule> CourseModule { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}
