//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.Questions = new HashSet<Questions>();
            this.HomeworkAssignements = new HashSet<HomeworkAssignements>();
        }
    
        public int AnswerId { get; set; }
        public string AnswerType { get; set; }
        public string AnswerValue { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<HomeworkAssignements> HomeworkAssignements { get; set; }
    }
}
