//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELearningDatabaseEntities : DbContext
    {
        public ELearningDatabaseEntities()
            : base("name=ELearningDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<CalendarEvents> CalendarEvents { get; set; }
        public DbSet<Conversations> Conversations { get; set; }
        public DbSet<CourseModule> CourseModule { get; set; }
        public DbSet<Courses> Courses { get; set; }
        public DbSet<Discussions> Discussions { get; set; }
        public DbSet<Forums> Forums { get; set; }
        public DbSet<Grades> Grades { get; set; }
        public DbSet<GroupMembers> GroupMembers { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<ModuleUser> ModuleUser { get; set; }
        public DbSet<Pages> Pages { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<Resources> Resources { get; set; }
        public DbSet<Syllabus> Syllabus { get; set; }
        public DbSet<Tests> Tests { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersInCourse> UsersInCourse { get; set; }
        public DbSet<HomeworkAssignements> HomeworkAssignements { get; set; }
        public DbSet<Homeworks> Homeworks { get; set; }
    }
}
