//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Homeworks = new HashSet<Homeworks>();
            this.Tests = new HashSet<Tests>();
            this.Users = new HashSet<Users>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupType { get; set; }
    
        public virtual ICollection<Homeworks> Homeworks { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
