//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> MesageData { get; set; }
        public Nullable<int> ForumId { get; set; }
        public Nullable<int> DiscusionId { get; set; }
        public Nullable<int> ConversationId { get; set; }
    
        public virtual Conversations Conversations { get; set; }
        public virtual Discussions Discussions { get; set; }
        public virtual Forums Forums { get; set; }
        public virtual Users Users { get; set; }
    }
}
