//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleUser
    {
        public int ModuleUserId { get; set; }
        public int CourseModuleId { get; set; }
        public string ModuleUserstatus { get; set; }
    
        public virtual CourseModule CourseModule { get; set; }
        public virtual Users Users { get; set; }
    }
}
