//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int ResourceId { get; set; }
        public string ResourceType { get; set; }
        public string FileLocation { get; set; }
        public Nullable<int> PageId { get; set; }
        public string FileId { get; set; }
        public string FileName { get; set; }
        public int CourseId { get; set; }
        public int ModuleID { get; set; }
    
        public virtual Pages Pages { get; set; }
    }
}
