//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeworkAssignements
    {
        public int AssignementId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseModuleId { get; set; }
        public Nullable<int> HomeworkId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<int> GradeId { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual CourseModule CourseModule { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Grades Grades { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Homeworks Homeworks { get; set; }
        public virtual Users Users { get; set; }
    }
}
